version: "3.2"
services:
    rabbitmq:
        container_name: "rabbitmq"
        image: rabbitmq:3-management-alpine
        volumes:
            - ./volum/rabbitmq/data/:/var/lib/rabbitmq/
            - ./volum/rabbitmq/log/:/var/log/rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - rabbitmq_go_net

networks: 
    rabbitmq_go_net:
        driver: bridge